from: ${PROFZONE_DOCKER_REGISTRY}/profzone/golang:runtime
image: ${PROFZONE_DOCKER_REGISTRY}/${PROJECT_GROUP}/${PROJECT_NAME}:${PROJECT_VERSION}
workdir: /go/bin
env:
  GOENV: DEV
  S_CONFIGAGENT_HOST: service-configurations.profzone.rancher.internal
  S_CONFIGAGENT_MODE: http
  S_CONFIGAGENT_PORT: "80"
  S_CONFIGAGENT_PULLCONFIGINTERVAL: "60"
  S_CONFIGAGENT_STACKID: "0"
  S_CONFIGAGENT_TIMEOUT: "5"
add:
  ./config: ./config
  ./profzone.yml: ./
  ./vehicle-robot-client: ./
expose:
- "80"
cmd:
- ./vehicle-robot-client
- -c=false
