GOENV: DEV
S_CONFIGAGENT_HOST: service-configurations.profzone.rancher.internal
S_CONFIGAGENT_MODE: http
S_CONFIGAGENT_PORT: "80"
S_CONFIGAGENT_PULLCONFIGINTERVAL: "60"
S_CONFIGAGENT_STACKID: "0"
S_CONFIGAGENT_TIMEOUT: "5"
S_MESSAGEBUS_REGISTERTOPICS: ""
S_ROBOTCLIENT_REMOTEADDR: 127.0.0.1:9090
